import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(new URL('..', import.meta.url).pathname);
const docsDir = path.join(root, 'docs');
fs.mkdirSync(docsDir, { recursive: true });
const checks=[]; const add=(name,ok,detail={})=>checks.push({name,ok:Boolean(ok),...detail});
const read=(rel)=>fs.readFileSync(path.join(root, rel), 'utf8');
const exists=(rel)=>fs.existsSync(path.join(root, rel));
for (const rel of ['server/index.mjs','shared/base.css','apps/public/home/index.html','apps/public/home/app.css','apps/public/documents/index.html','apps/public/plans/index.html','Dockerfile','package.json']) add(`exists:${rel}`, exists(rel));
const server=read('server/index.mjs');
for (const route of ['/', '/plans', '/documents', '/products/veridion/demo', '/checkout', '/portal', '/board', '/business-info']) add(`route:${route}`, server.includes(`'${route}'`) || route==='/');
for (const api of ['/api/public/products','/api/public/document-preview','/api/public/checkout-session','/api/public/payment/complete','/api/public/fulfillment','/healthz']) add(`api:${api}`, server.includes(api));
for (const offer of ['Report','FixPack','TemplatePack','IndustryGuide','Basic','Pro','Auto','Certified','Agency']) add(`offer:${offer}`, server.includes(`'${offer}'`) || server.includes(`code: '${offer}'`));
const home=read('apps/public/home/index.html');
for (const token of ['VERIDION','무료 문서 초안 생성','웹사이트 운영 리스크','상세 정보는 전용 페이지','예시 기본값 없이']) add(`home:${token}`, home.includes(token));
const homeCss=read('apps/public/home/app.css');
for (const token of ['hero-board','document-panel','scope-row','compact-sections','quick-links','trust-icons']) add(`home-css:${token}`, homeCss.includes(token));
const docs=read('apps/public/documents/index.html');
add('documents:blank-defaults', !docs.includes('엔브이제로(NV0)') && !docs.includes('나금상') && !docs.includes('경기도 남양주시'));
add('documents:placeholder', docs.includes('상호를 입력하세요') && docs.includes('이메일을 입력하세요'));
const base=read('shared/base.css');
add('nav:brand-polish', base.includes('brand-mark') && server.includes('VERIDION'));
const allClient = fs.readdirSync(path.join(root,'apps/public'), {withFileTypes:true}).filter(d=>d.isDirectory()).map(d=>['index.html','app.js','app.css'].map(f=>`apps/public/${d.name}/${f}`)).flat().filter(exists).map(read).join('\n');
add('client:no-console-log', !/console\.log\(/.test(allClient));
add('client:no-inline-handler', !/\son[a-z]+\s*=/.test(allClient));
add('runtime:sessions-empty', read('runtime/data/sessions.json').trim()==='[]');
add('runtime:db-seed-match', read('runtime/data/db.json')===read('runtime/data/db.seed.json'));
for (const dir of ['runtime/uploads','runtime/backups','runtime/reports']) add(`runtime:${dir}:empty`, !exists(dir) || fs.readdirSync(path.join(root,dir)).length===0);
const ok=checks.every(c=>c.ok); const report={generatedAt:new Date().toISOString(), ok, phase:'phase27-distributed-uiux-truthful-copy', total:checks.length, passed:checks.filter(c=>c.ok).length, failed:checks.filter(c=>!c.ok).length, checks};
fs.writeFileSync(path.join(docsDir,'PHASE27_TEST_ALL_SUMMARY_20260424.json'), JSON.stringify(report,null,2));
console.log(JSON.stringify({ok, passed:report.passed, failed:report.failed, report:'docs/PHASE27_TEST_ALL_SUMMARY_20260424.json'}, null, 2));
process.exit(ok?0:1);
